### ISSUE TITLE
Apimancer's drainer does not work well with anything

### ISSUE THREAD

**Issue by moonlee7777** [Alastors/AlastorsIssues#1]
**Describe the bug**
Drainer does not interact with import bus directly and import bus does not work on essentia tubes

**What Mods?**
Magic Bees and Thaumistic Energistics

**What Version (if GTNH)**
2.6

**To Reproduce**
Put down aforementioned blocks

**Expected behavior**
These should all connect

**Additional context**

**Comment by Alastors** [comment]
Thanks, I'll take a look at it
