### ISSUE TITLE
The great magic endgame (Suggestion)

### ISSUE THREAD

**Issue by joseoton** [Alastors/AlastorsIssues#10]
**Describe the feature**

Disclaimer: This is just a esketch.

I would like to suggest a new final goal for magic in the quest book, to encourage people to invest in magic plus give a reward to people that rlly enjoy it. The stuff I will talk bout could be added in either a new tab or with small upgrades to the alredy existant ones.

Currently we have 5 mayor magic mods: Thaum, BM, Botania, Witchery and HEE.

The rewards for the tasks Ill later describe could be a new way to get the "creative magic items" in zpm (Where you can complete every single quest in the magic tabs at this point aside from Akashic and Armok) or a magic stone per each mod, for example: Purple stone for HEE, Red for BM, Green for Botania, Blue for witchery and Yellow for thaumcraft. And if you gather them all u can assemble some cool op item or statue/decoration and perhaps a new discord role ( I know this is a hard one but as we have a stargate role for tech endgame and quest master for quest completion it would be awesome to have a specific role for magic and forestry completions)

**HEE**

HEE has alredy a great late game implementations with charm/curse master and master grinder, I would suggest just a quest with a checkbox called "End's Legacy" that needs master grinder and hot puzzle quests to unlock and awards you just the Purple Stone as a reward.

**BM**

The final quest here would be called "Bloodline Apex" and require all the sigil quests plus the eldritch blood orb, to complete this quest you need any set of the omega armor. A possible reward could be the Red Stone, the Blood Orb of Armok or both (Infinite lp is not op at this point when u probably have alredy a WA Well of Suffering, and this allows you to complete the quest tab without waiting 2 entire energy tiers)
Quick note: Every sigil implemented is in a quest except for sigil of sight, but it is needed for the ritual diviner.

**Botania**

In this tab I would suggest a few changes, Firstly 2 new simple quests to compile the rest of the flowers (not counting the decorative ones nor Asgardandelion), one after Jaded Amaranthus that compiles all the functional + Hiveacynth and Hibeescus, and the second one after "Better Generating Flowers" that would require the rest of the generating flowers + Beegonia (Manastar could be added wherever); the final quest requires this 2 new ones, "runes" and "Round two... FIGHT!" and will be called "Bloom of Eternity", to complete it u need the 6 gaia artifacts and the rewards could be the Green Stone, an Asgardandelion or both, I think its a fair reward after collecting all the flowers and getting the artifacts.
Important note: It's important to let people know that u can get Enderlotus, Waterlily or Miner's Delight via bees and that the only way you can get Deathbloom is changing biomes to Ominous woods with witchery and using bone meal in the floor. And that if you use ichor armor vs gaia the game breaks.

**Witchery**

This one is tricky, there are practically no documentation online atm for some bosses and some of the related quests are in the Kill all the things tab. Anyway the final quest here is "Cauldron of Shadows" and the prerequisites are "Be a vampire: Dress Like a Fancy Person" (This compiles Mog Gulg and Baba Yaga kills) , "Lord of Torment", "Mellifluous Hunger" and "Kill Shade of Leonard" (From Kill All the Things tab) this quest could be just a checkbox or mayke kill "Death" boss and the rewards are same as earlier, infinity egg, Blue Stone or both.

**Thaumcraft**

With the focus on Wand Foci tab it would be weird to make a quest requiring like 30 of the remaining focus, and a complete rework of the tab would be a lot of work probably so my suggestion here is that the prerequirements for the new final quest "Eldritch Ascension" are the quests "Wand focus Tainted Shockwave", "Wand Focus Dark Matter", every "Unleashed the power" quest and "Best wand". The rewards could be Akashic Records (This let u complete the ichor tab), the Yellow Stone or both probably the infinite wand would be to much.

If the late game items as rewards end up happening the prerequirement should be removed for akashic and Armok.

Tbh probably is just better the "Stone" sistem as reward (Kinda like kuba teas) than the lategame items, but in that case either akashic or armok should be removed from the magic tabs or the infinity egg, the everlasting pool... should be added to their respectives magic tabs.

I hope you like the idea Alastor, idk if the work this would take would be too much to handle it alone, and this is somewhat the general idea, if you end up liking it dont doubt to dm me on discord @jose_oton so I could help in anything.

**Comment by Alastors** [comment]
HEE isn't a magic mod

**Comment by Alastors** [comment]
Same to similar reasons why DE isn't

**Comment by joseoton** [comment]
Yeah, kind of but as it has an entire tab, 5 is a cool number and it alredy has some hard quests I thought it would be a great addition to the suggestion

**Comment by Alastors** [comment]
Not actually against the idea of finishing all of magic to get a role, but that'd be up to boubou, I'll propose the idea tho

**Comment by Alastors** [comment]
> Yeah, kind of but as it has an entire tab, 5 is a cool number and it alredy has some hard quests I thought it would be a great addition to the suggestion

Sure, tho for the intents and purposes of GTNH, it isn't, but I def could make a 4 piece stone thing

**Comment by joseoton** [comment]
> Not actually against the idea of finishing all of magic to get a role, but that'd be up to boubou, I'll propose the idea tho

I proposed an idea similar for completing the entire Full Genome Project and it was rejected and that one was like 10x times harder so I wouldnt be as optimistic

**Comment by Alastors** [comment]
I mean finishing all of thaum is at least UMV since it has a couple items up there so

**Comment by joseoton** [comment]
No idea of which ones, anyway this was just a general idea from a collectionist

**Comment by joseoton** [comment]
Im sure there are plenty of better choices to do the stuff I proposed

**Comment by joseoton** [comment]
By the way, I know you are a perfectionist, and so am I. I would like to help with anything related to this topic, so please don’t hesitate to contact me for feedback or anything else.

**Comment by Alastors** [comment]
Lmfao, I'm just waiting for a yes or no from boubou, then I'll draft something up along these lines

**Comment by Alastors** [comment]
Was denied

**Comment by Alastors** [comment]
I'll consider it as just a general magic quest, but I'm going to close this for the time being, sorry man

**Comment by joseoton** [comment]
Unlucky I guess, a magic role would have been nice, nonetheless a cool item or decoration as a final magic reward would be cool, yet I understand this is a lot of work, it is sad sometimes to get ideas rejected, I still really value all the work you do for magic, tnx for considering it man!!!

**Comment by Alastors** [comment]
Yeah man! I might revisit this in the future with a modeled trophy or something, but at the moment that's a bit out of my ability and modelers are hard to find, so perhaps eventually
