### ISSUE TITLE
EMT is using ModularUI 1

### ISSUE THREAD

**Issue by kappa-maintainer** [Alastors/AlastorsIssues#11]
**Describe the bug**
[EMT](https://github.com/GTNewHorizons/Electro-Magic-Tools) is using ModularUI 1 (which it shouldn't) and will be incompat with mods using ModularUI 2
The PR introduce MUI: https://github.com/GTNewHorizons/Electro-Magic-Tools/pull/52

**Comment by Alastors** [comment]
God I hate when we add shit that has no reason to be used for cases like this. 

Yeah should be simple enough to undo the damage

**Comment by Alastors** [comment]
Okay, we talked to the main dev of MUI, he said he'd see what he can do for MUI compatibility, worst case scenario I'll push a MUI removing PR for EMT
