### ISSUE TITLE
Broken recipe

### ISSUE THREAD

**Issue by dagger8243** [Alastors/AlastorsIssues#15]
GTNH 2.6.1

Thaumic snowball from witching gadgets has broken recipe, below are thaumonomicon entry and what NEI says recipe is

![image](https://github.com/Alastors/AlastorsIssues/assets/44447392/b5d5db03-a4f1-4ca9-b3d2-32d79c733472)
![image](https://github.com/Alastors/AlastorsIssues/assets/44447392/32c49381-04ff-45ea-a0cb-22051d086e37)

**Comment by EnderProyects** [comment]
I have done that recipe one time, make sure that you are looking for the same block since there is a block that makes ice that have the same texture and similar name

**Comment by Alastors** [comment]
Oh shit you're right

**Comment by Alastors** [comment]
Wasn't that
