### ISSUE TITLE
Blood magic weird altar tier

### ISSUE THREAD

**Issue by dagger8243** [Alastors/AlastorsIssues#16]
[GTNH 2.6.1]

When i break the a rune off the t3 ring the altar drops down to t1 rather than t2

![image](https://github.com/Alastors/AlastorsIssues/assets/44447392/f29587de-f827-4ec4-b312-8eb23480fee3)

When i break a rune off the t4 ring the altar drops down to t3 as it should tho

![image](https://github.com/Alastors/AlastorsIssues/assets/44447392/e98c0f09-a586-4d2e-a618-b80f47094423)

When i break a rune off the t5 ring the altar drops down to t4 as it should as well so looks to be an issue with t3 ring specifically

**Comment by Superfrogman98** [comment]
This could be because of the non-blank runes in the corners of the t2 ring, from what I remember they’ve only been upgradable once the altar is t3+
