### ISSUE TITLE
Only thauminite nuggets have aspects

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [Alastors/AlastorsIssues#23]
**Describe the bug**
Only thauminte nuggets have aspects, ingots and blocks dont.
**Screenshots?**
![image](https://github.com/user-attachments/assets/834999aa-8c1b-4980-9db8-a9730cf98d76)
![image](https://github.com/user-attachments/assets/a0925feb-d4d4-4852-a488-aa87ebd68845)
![image](https://github.com/user-attachments/assets/536cf91e-6cb9-4499-9be8-d0e3c0089eba)

**What Mods?**
Thaumic bases
**What Version (if GTNH)**
Any of the latest
**To Reproduce**
hover over THauminite items with the thaumometer
**Expected behavior**
The ingots and blocks would have aspects
**Additional context**
It's prob cuz the autogeneration caught the thaumium ingot -> thauminite nuggets, but didn't get the thauminite nuggets to ingots and blocks.

**Comment by Alastors** [comment]
Wild I swear this didn't used to be the case

**Comment by LazyFleshWasTaken** [comment]
Been like that since at least 2.4.0 just remembered about it now and had the motivation to report it.
