### ISSUE TITLE
Wand focus Blink + AE Wrench issue

### ISSUE THREAD

**Issue by joseoton** [Alastors/AlastorsIssues#3]
**Describe the bug**

The wand focus: Blink and the wand focus: AE wrench looks like they are mutually excluse, doesnt matter if they are in a bottomless pouch or just in your inventory, only the first one that entered your inventory is the one that is shown in the wand menu, sometimes wthen u drop them/take them out of your inventory and recollecting them they swap and is the other the one that is appearing but this seems kinda random

**Screenshots?**

![image](https://github.com/Alastors/AlastorsIssues/assets/131607623/e39477b3-2e21-4536-94d6-dba431906f9c)

**What Mods?**

Forbidden Magic + Thaumic Energistics

**What Version (if GTNH)**

2.5.1

**To Reproduce**

Just have both focus in your inventory

**Expected behavior**

The 2 focus appear in the wand wheel

**Additional context**

Just for themselves they show fine but when they are together they bug

**Comment by Alastors** [comment]
Lmfao that's super weird, I wonder if they have some internal metadata similarities

**Comment by joseoton** [comment]
I mean it is not like a super game changing bug, but still a bug
