### ISSUE TITLE
Jetpack Hover mode and Boots of the Meteor Ground Pound Conflict

### ISSUE THREAD

**Issue by EdenExecutive** [Alastors/AlastorsIssues#5]
**Describe the bug**

Landing whilst using hover mode with Advanced nanochestplate causes ground pound effect (explosion) from boots of the Meteor and its variants. Testing with Advanced Jetpack and Qauntumsuit jetpack shows same result, Gravichestplace does not however. No other jetpacks were tested.

**What Mods?**

Thaumic boots and technically Graviation Suite and IC2

**What Version (if GTNH)**

2.6.0

**To Reproduce**

Take any of the mentioned jetpack options and variants of the boots of the Meteor, turn on the jetpack and set it to hover mode, use the sneak key to descend to the ground, explosion occurs.

**Expected behavior**

For the ground pound effect not to occur when you're coming in for a smooth and gentle landing.

**Comment by Alastors** [comment]
Can you test with the normal boots of the meteor and see if this still happens?

**Comment by Alastors** [comment]
Oh wait you seem to have already I assume

**Comment by Alastors** [comment]
I'll look into adding a toggle for the TX effects

**Comment by EdenExecutive** [comment]
I'm not very familiar with coding so i wouldn't know how hard it would be, but maybe an option would be for the effect to not occur as long as the speed along the Y-axis of a player doesn't exceed a certain value?

A toggle would also work though, just thought it might be nice to be able to preserve the effect when you're actually coming in fast.

**Comment by Alastors** [comment]
Tbf I mostly bring up the toggle because it's been requested for the sister effect anyway 🤷‍♂️

We'll see I suppose
