### ISSUE TITLE
Huge TPS impact from thaumcraft.common.blocks.BlockMagicalLeaves.updateTick()

### ISSUE THREAD

**Issue by Darkmaxsas** [Alastors/AlastorsIssues#7]
Soooo, not sure if this is the right place to report this since i dont really know what part of, and if, Thaumcraft is the source of this.

**Describe the bug**

Noticed huge TPS impacts since updating to GTNH 2.6.0. I could track it down using spark and something called thaumcraft.common.blocks.BlockMagicalLeaves.updateTick() seems to be causing it

**Screenshots?**

<img width="1266" alt="Unbenannt" src="https://github.com/Alastors/AlastorsIssues/assets/98653930/e78476a9-134b-4376-9d0c-1f5bceb7dd6d">

<img width="1256" alt="Unbenannt" src="https://github.com/Alastors/AlastorsIssues/assets/98653930/d0acea50-c7bf-49b4-a7e6-0c1b7a1c4b0f">

**What Mods?**

Thaumcraft (i think?)

**What Version (if GTNH)**

2.6.0

**To Reproduce**

**Expected behavior**

**Additional context**

let me know if something other than TC is causing this so i can report it at the right place.
Many a thanks :D

**Comment by Alastors** [comment]
Thaumcraft, unfortunately, is insanely laggy as a whole, it's something I'm hoping to fix in the rewrite, but there's not really anything I can do to change it directly, sorry
